### ISSUE TITLE
Unittest fails on Windows with Python 3.7

### ISSUE THREAD

**Issue by matthiasbock** [cvra/packager#17]
* python -m unittest
<pre>
.F...F............FF...FFF......FF.........
======================================================================
FAIL: test_dependencies_filemap (tests.tests_dependency_download.DependencyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 1175, in patched
    return func(*args, **keywargs)
  File "packager\tests\tests_dependency_download.py", line 145, in test_dependencies_filemap
    self.clone.assert_any_call('https://github.com/cvra/pid', 'foo/pid')
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 872, in assert_any_call
    ) from cause
AssertionError: mock('https://github.com/cvra/pid', 'foo/pid') call not found

======================================================================
FAIL: test_dependency_has_a_dependency_itself_filemap (tests.tests_dependency_download.DependencyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 1175, in patched
    return func(*args, **keywargs)
  File "packager\tests\tests_dependency_download.py", line 94, in test_dependency_has_a_dependency_itself_filemap
    self.clone.assert_any_call('https://github.com/cvra/pid', 'foo/pid')
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 872, in assert_any_call
    ) from cause
AssertionError: mock('https://github.com/cvra/pid', 'foo/pid') call not found

======================================================================
FAIL: test_load_filemap (tests.tests_misc.OpenPackageTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "packager\tests\tests_misc.py", line 37, in test_load_filemap
    m.assert_called_with('foo/pid/package.yml')
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 810, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: open('foo/pid/package.yml')
Actual call: open('foo\\pid\\package.yml')

======================================================================
FAIL: test_load_simple_package (tests.tests_misc.OpenPackageTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "packager\tests\tests_misc.py", line 25, in test_load_simple_package
    m.assert_called_with('dependencies/pid/package.yml')
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 810, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: open('dependencies/pid/package.yml')
Actual call: open('dependencies/pid\\package.yml')

======================================================================
FAIL: test_path_for_package_with_a_map (tests.tests_package_path.PackageNameTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "packager\tests\tests_package_path.py", line 49, in test_path_for_package_with_a_map
    self.assertEqual("control/pid", path_for_package(package, m))
AssertionError: 'control/pid' != 'control\\pid'
- control/pid
?        ^
+ control\pid
?        ^

======================================================================
FAIL: test_pkgfile_complex_case (tests.tests_package_path.PackageNameTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "packager\tests\tests_package_path.py", line 28, in test_pkgfile_complex_case
    self.assertEqual(expected, pkgfile_for_package(package))
AssertionError: 'dependencies/pid/package.yml' != 'dependencies/pid\\package.yml'
- dependencies/pid/package.yml
?                 ^
+ dependencies/pid\package.yml
?                 ^

======================================================================
FAIL: test_pkgfile_trivial_case (tests.tests_package_path.PackageNameTest)
Checks that we can correctly generate the package file path.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "packager\tests\tests_package_path.py", line 20, in test_pkgfile_trivial_case
    self.assertEqual(expected, pkgfile_for_package(package))
AssertionError: 'dependencies/pid/package.yml' != 'dependencies/pid\\package.yml'
- dependencies/pid/package.yml
?                 ^
+ dependencies/pid\package.yml
?                 ^

======================================================================
FAIL: test_source_in_filemap (tests.tests_source_list.GenerateSourceListTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 1175, in patched
    return func(*args, **keywargs)
  File "packager\tests\tests_source_list.py", line 40, in test_source_in_filemap
    self.assertEqual(['./application.c', 'foo/pid/pid.c'], result)
AssertionError: Lists differ: ['./application.c', 'foo/pid/pid.c'] != ['./application.c', 'foo\\pid\\pid.c']

First differing element 1:
'foo/pid/pid.c'
'foo\\pid\\pid.c'

- ['./application.c', 'foo/pid/pid.c']
?                         ^   ^

+ ['./application.c', 'foo\\pid\\pid.c']
?                         ^^   ^^

======================================================================
FAIL: test_source_package_dep (tests.tests_source_list.GenerateSourceListTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\unittest\mock.py", line 1175, in patched
    return func(*args, **keywargs)
  File "packager\tests\tests_source_list.py", line 58, in test_source_package_dep
    self.assertEqual(sorted(expected), sorted(result))
AssertionError: Lists differ: ['./application.c', 'dependencies/pid/pid.c'] != ['./application.c', 'dependencies/pid\\pid.c']

First differing element 1:
'dependencies/pid/pid.c'
'dependencies/pid\\pid.c'

- ['./application.c', 'dependencies/pid/pid.c']
?                                      ^

+ ['./application.c', 'dependencies/pid\\pid.c']
?                                      ^^

----------------------------------------------------------------------
Ran 43 tests in 0.043s

FAILED (failures=9)
</pre>

**Comment by antoinealb** [comment]
Hi,

Thanks for the report. Does it work on Windows with previous Python version, e.g. 3.5 or 3.6?

**Comment by matthiasbock** [comment]
Don't know, I would have to test that...

Looks like a path separator problem to me:
In packager.py you're using os.path.join() to join path segments,
while in the tests you have "/" hardcoded as a separator.

**Comment by antoinealb** [comment]
Yes, this was also my guess, hence my question about if it was a regression with Python 3.7 or if it was a bug.

I think the easiest might be to fix the separator in the tests.

**Comment by antoinealb** [comment]
Could you please test the PR #18 on your setup ? I don't have a windows machine nearby.

**Comment by matthiasbock** [comment]
Will do...

**Comment by matthiasbock** [comment]
The number of failures is reduced to 6, but still the same problem occurs.

**Comment by matthiasbock** [comment]
The problem is fixed by commit https://github.com/matthiasbock/cvra-packager/commit/04e3c88ff2e20eea98cb9ef1c3c4e928fce3fd70.
Feel free to merge :-)
