### ISSUE TITLE
packager raises exception when run with Python 2.7

### ISSUE THREAD

**Issue by matthiasbock** [cvra/packager#19]
When run outside a project folder (containing a package.yml) with Python 2.7, packager.py failes with an exception:
````sh
$ cvra-packager/cvra_packager/packager.py
Traceback (most recent call last):
  File "cvra-packager/cvra_packager/packager.py", line 274, in <module>
    main()
  File "cvra-packager/cvra_packager/packager.py", line 248, in main
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
````

The reason is, that FileNotFoundError doesn't exist in Python 2.7. With Python 3.7 it properly returns:
````sh
package.yml was not found. Did you forget to git add it ?
````

It would be nice, if packager wouldn't raise an exception, but rather print a nice error message, when run with an incompatible Python version, something like:
````Python
import sys
if sys.version_info < (3, 0):
    raise "Sorry, you're running an incompatible Python version. Packager must be run with Python 3.x."
````

This would make it more convenient to use for users and developers, who are not that familiar with Python and it's versions.

**Comment by antoinealb** [comment]
Hello,
Thanks for the report. Unfortunately making Python code compatible with both 2 & 3 can be a pain and our team decided early on to only support Python 3, especially since we are so close to the [EOL of the 2.7 series](https://pythonclock.org/). 

So far what we have is a tag in the `setup.py` to inform the user that the code is not Python 2 compatible but it is not enforced by pip. Do you think adding your example code at install time would be an OK compromise ?

**Comment by matthiasbock** [comment]
I understand. So, if the user installs via pip, then there will be a message. That's good.
But what if I clone the repo and run packager.py manually?
I think, packager should be able to detect and handle version problems itself, too.
I mean, not to add support for Python 2, but to print a helpful message at startup, no?

**Comment by antoinealb** [comment]
> But what if I clone the repo and run packager.py manually?

That would still cause dependencies issues, wouldn't it ? (Jinja, yaml, etc).

> I mean, not to add support for Python 2, but to print a helpful message at startup, no?

Could be feasible. I am just wondering if the best is to detect it at runtime or at install time ?

**Comment by matthiasbock** [comment]
>>   But what if I clone the repo and run packager.py manually?

> That would still cause dependencies issues, wouldn't it ? (Jinja, yaml, etc).

That is true. However, the difference is, that those issues (when attempting to start packager.py manually) generate nice error messages, from which a non-experienced user can derive, that those packages should be installed. The 'FileNotFoundError' exception on the other hand doesn't say that another Python version should be used and thus leaves the non-experienced user perplexed as to why the packager "doesn't work".

>>  I mean, not to add support for Python 2, but to print a helpful message at startup, no?

> Could be feasible. I am just wondering if the best is to detect it at runtime or at install time ?

Well, in the end, you have to decide. My suggestion would be to have both because of the two ways packager can be obtained (by cloning the repo or via pip).

**Comment by antoinealb** [comment]
Ok, I implemented this and am uploading a fixed version on PyPI.

**Comment by matthiasbock** [comment]
Awsome. Thank you.
